services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-staging
    environment:
      NODE_ENV: staging
      DB_URL: ${DB_URL}
      MONGO_URI: ${MONGO_URI}
      REDIS_URL: ${REDIS_URL}
    ports:
      - "3001:3000"
    restart: always
